src/main/java/toyproject/runningmate/controller/BoardController.java, src/main/java/toyproject/runningmate/domain/Address.java, src/main/java/toyproject/runningmate/domain/Board/Board.java, src/main/java/toyproject/runningmate/dto/BoardDto.java, src/main/java/toyproject/runningmate/service/BoardService.java
지역 세 개 값에 따른 지역별 조회 기능
지역이 하나도 선택되지 않은 경우 모든 게시글 조회
close #3
=> feat : 게시글 지역 조회

src/main/java/toyproject/runningmate/controller/CommentController.java, src/main/java/toyproject/runningmate/domain/comment/Comment.java, src/main/java/toyproject/runningmate/dto/CommentDto.java, src/main/java/toyproject/runningmate/repository/CommentRepository.java, src/main/java/toyproject/runningmate/service/CommentService.java
=> feat : 댓글 생성 기능

src/main/java/toyproject/runningmate/domain/Board/Board.java, src/main/java/toyproject/runningmate/dto/BoardDto.java
FE에서 게시판 생성에서 글 작성자 데이터 요청
Board, BoardDto에 author 추가
close #13
=> chore : Board, BoardDto에 작성자 추가

src/main/java/toyproject/runningmate/controller/CommentController.java, src/main/java/toyproject/runningmate/service/CommentService.java
=> feat : 댓글 수정 기능 api 구현

src/main/java/toyproject/runningmate/controller/CommentController.java, src/main/java/toyproject/runningmate/service/CommentService.java
=> feat : 댓글 삭제 기능

src/main/java/toyproject/runningmate/controller/CommentController.java, src/main/java/toyproject/runningmate/service/CommentService.java
게시판을 조회할 때, 해당 게시판 id에 따른 댓글들 조회
close #21
=> feat : 게시판 댓글 조회

src/main/java/toyproject/runningmate/controller/CrewController.java, src/main/java/toyproject/runningmate/service/CrewService.java
CrewController의 기존 api를 restful하게 수정
offset과 limit를 이용하여 FE가 쉽게 페이징 이용하도록 수정
close #30
=> feat : Crew api 및 Crew 조회 페이징 수정

.gitignore, src/main/java/toyproject/runningmate/controller/FriendShipController.java
친구수락 API 삭제하고 친구버튼 API랑 통합
FriendShip API 주소 노션과 같게 전체 수정
close #31
=> Chore : FriendShip API 수정

src/main/java/toyproject/runningmate/controller/UserController.java
=> feat : user api rest하게 수정

src/main/java/toyproject/runningmate/controller/CrewController.java, src/main/java/toyproject/runningmate/service/CrewService.java
leader를 조회할 때 join fetch를 이용하여 crew를 즉시로딩하여 최적화 진행
closed #48
=> refactor : 크루장 위임 쿼리 최적화

src/main/java/toyproject/runningmate/domain/user/User.java, src/main/java/toyproject/runningmate/service/CrewService.java
기존 코드는 user입장에서 crew만 없앰
crew 입장에서 가입된 Users에서 삭제 추가
close #51
=> fix : 크루원 추방, 탈퇴 api 수정

src/main/java/toyproject/runningmate/controller/CrewController.java, src/main/java/toyproject/runningmate/service/CrewService.java, src/main/java/toyproject/runningmate/service/UserService.java
필요한 데이터만 service에 전송
controller가 아닌 service에서 검증 진행
이로 인해 필요없는 UserService 메서드 삭제
close #53
=> refactor : 크루 저장 api 쿼리 최적화

src/main/java/toyproject/runningmate/controller/UserController.java
Reverts Runvengers/RunningMate#42
=> Revert "#34"

src/main/java/toyproject/runningmate/controller/UserController.java
Reverts Runvengers/RunningMate#41
=> Revert "feat : user api rest하게 수정"

src/main/java/toyproject/runningmate/controller/UserController.java, src/main/java/toyproject/runningmate/domain/user/User.java, src/main/java/toyproject/runningmate/dto/LoginDto.java, src/main/java/toyproject/runningmate/dto/UserDto.java, src/main/java/toyproject/runningmate/service/UserService.java
UserController에서 기능을 구현하지 않고 UserService에서 구현
UserDto, LoginDto, User의 의존도를 낮추기 위해 리팩토링
매개변수를 객체로 바꾸어 코드 간결성
closed #66
closed #35
=> refactor : 로그인 api 리팩토링

src/main/java/toyproject/runningmate/controller/FriendShipController.java
requestName -> request-name으로 수정
=> chore : FriendShip API URI 수정

src/main/java/toyproject/runningmate/controller/UserController.java, src/main/java/toyproject/runningmate/domain/crew/Crew.java, src/main/java/toyproject/runningmate/domain/user/User.java, src/main/java/toyproject/runningmate/dto/CrewDto.java, src/main/java/toyproject/runningmate/dto/LoginDto.java, src/main/java/toyproject/runningmate/dto/UserDto.java, src/main/java/toyproject/runningmate/service/CrewService.java, src/main/java/toyproject/runningmate/service/UserService.java
이미지의 URL을 넣기 위해 User와 Crew 클래스 및 각 DTO에 image 필드 추가
closed #68
=> feat : User,Crew Entity에 image 필드 추가

src/main/java/toyproject/runningmate/controller/UserController.java
=> feat : 토큰 유효성 검사 API 추가

src/main/java/toyproject/runningmate/controller/UserController.java, src/main/java/toyproject/runningmate/service/UserService.java
토큰 유효성 검사 로직을
Controller->Service로 레이어 변경
=> chore : 토큰 유효성 검사 API 수정

src/main/java/toyproject/runningmate/controller/CrewController.java
CrewController에서 토큰에서 정보를 꺼낼 때 이메일로 꺼내서 버그 발생
닉네임으로 변환 뒤 요청 저장
closed #80
=> fix : crew 정보 조회 시 요청목록에 이메일 -> 닉네임 수정

src/main/java/toyproject/runningmate/controller/CrewController.java, src/main/java/toyproject/runningmate/domain/crew/Crew.java, src/main/java/toyproject/runningmate/service/CrewService.java
crew의 image, explanation, crewRegion, openChat을 변경할 수 있는 api 추가
closed #83
=> feat : crew 정보 수정 추가

src/main/java/toyproject/runningmate/controller/UserController.java, src/main/java/toyproject/runningmate/domain/user/User.java, src/main/java/toyproject/runningmate/service/UserService.java
user의 image를 수정할 수 있게 추가
closed #86
=> feat : user image update 추가
